prefix ex: <http://example.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix actorODP: <http://w3id.org/CEON/ontology/actorODP/> 
prefix dppODP: <http://w3id.org/dppo/ontology/dpp-odp/> 
prefix resourceODP: <http://w3id.org/CEON/ontology/resourceODP/> 
prefix maintenance: <http://example.org/maintenance/> 
prefix plcs: <http://www.plcs.org/plcslib/plcslib/data/PLCS/concept_model/> 

SELECT ?heat_pump ?service ?maintain_time ?person WHERE {
  ?maintain_activity a maintenance:MaintenanceActivity ;
   maintenance:maintainedOn ?heat_pump ;
   maintenance:maintainTime ?maintain_time ;
   maintenance:maintainedBy ?person ;
   maintenance:maintainService ?service.
  ?observation plcs:observedProduct ?heat_pump.
  ?observation  ex:EMON_EL_APPLIANCE_DT255_943_I0-3  ?value .
  FILTER (?value>"3000")
}
Order By ?maintain_time